### ISSUE TITLE
Item linking sometimes displays duplicates/previous items

### ISSUE THREAD

**Issue by Dingf** [Dingf/GDCommunityLauncher#5]
For specific users, linked items will sometimes be displayed as an item that was previously linked instead of the actual linked item. Currently no known way to reproduce this issue reliably.

**Comment by 12foo** [comment]
From a conversation in chat right now, seems this is an issue for the receiver, not the sender.

**Comment by 12foo** [comment]
Also this just happened to me, and directly after, I had a freeze/crash. Maybe they are related. I'll have a look.

**Comment by 12foo** [comment]
So far I can confirm that is is definitely clientside; the server is sending different items over the wire but the client is displaying the same one(s).

**Comment by Dingf** [comment]
This issue is most likely resolved with the following change:

https://github.com/Dingf/GDCommunityLauncher/blob/9dce3e0ddf020b044e08956ffd189db22c69bda8/dll/src/ChatClient.cpp#L114

Previously, the launcher was reusing the same item ID when generating item links, which probably resulted in the system returning a cached copy of the item rather than creating a new one for performance reasons. A similar issue was observed when recreating items in the shared stash, where if a separate item ID is not provided, the item created would often be a duplicate of another.

I have also not heard of anybody experiencing this issue this season, so I will close this issue for now.
